# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now=True)),
                ('is_board', models.CharField(choices=[('1', 'Member'), ('2', 'Board Member')], default='2', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(max_length=2000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventReviews', to='backend.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricNo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(through='backend.Membership', to='backend.Student'),
        ),
        migrations.AddField(
            model_name='review',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to='backend.Student'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Student'),
        ),
        migrations.AddField(
            model_name='membership',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Society'),
        ),
        migrations.AddField(
            model_name='event',
            name='attended_by',
            field=models.ManyToManyField(related_name='attended_by', to='backend.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='organized_by',
            field=models.ManyToManyField(related_name='organized_by', to='backend.Society'),
        ),
    ]
