# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190318_1655'),
        ('backend', '0002_auto_20190318_1533'),
    ]

    operations = [
    ]
